language: python
python:
  - '3.7'
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python manage.py test
  - coverage run --source=. --omit=manage.py --rcfile=setup.cfg manage.py test
after_success: coveralls
